# Generated by Django 2.2.3 on 2019-08-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('식품', '식품'), ('가구/생활/건강', '가구/생활/건강'), ('디지털/가전', '디지털/가전'), ('의류/잡화', '의류/잡화'), ('뷰티', '뷰티'), ('도서/취미/상품권', '도서/취미/상품권'), ('레저/자동차', '레저/자동차'), ('반려동물', '반려동물')], max_length=10)),
                ('writer', models.CharField(max_length=10)),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content', models.TextField(blank=True, null=True)),
                ('buyitnow', models.PositiveIntegerField(default=0)),
                ('up_price', models.PositiveIntegerField(default=0)),
                ('lookup', models.PositiveIntegerField(default=0)),
                ('e_date', models.DateTimeField(verbose_name='date published')),
                ('biddings', models.CharField(default="{u'li':[]}", max_length=200)),
                ('confirm', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1, null=True)),
                ('comment', models.CharField(max_length=30, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Write')),
            ],
        ),
        migrations.CreateModel(
            name='Addsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
